spring:
  jpa:
    open-in-view: true
    hibernate:
      generate-ddl: true
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000 # in 절
        dialect: org.hibernate.dialect.MySQL8Dialect

 # Database
  datasource:
    url: jdbc:mysql://localhost:3306/yunshinshop   #mysql포트번호/디비이름
    username: yunshinshop
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
